# Generated by Django 4.0.1 on 2022-01-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_fighters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fighters',
        ),
    ]
