# Generated by Django 4.0.1 on 2022-01-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_fighters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='end_carrier1',
        ),
    ]
